swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "Minter Node API"
  contact:
    email: "dl@minter.org"
  license:
    name: "MIT"
    url: "https://github.com/MinterTeam/minter-go-node/blob/master/LICENSE"
host: "localhost:8841"
basePath: "/"
schemes:
  - "http"
paths:
  /address:
    get:
      summary: "Get balance and transaction count of given address"
      description: ""
      operationId: "address"
      produces:
        - "application/json"
      parameters:
        - name: "address"
          in: "query"
          description: "Minter Address, starts with Mx..."
          required: true
          type: string
      responses:
        200:
          schema:
            $ref: "#/definitions/AddressResponse"
  /status:
    get:
      summary: "Get overall status of Minter Node"
      description: ""
      operationId: "status"
      produces:
        - "application/json"
      responses:
        200:
          schema:
            $ref: "#/definitions/StatusResponse"
definitions:
  AddressResponse:
    type: "object"
    properties:
      jsonrpc:
        type: string
        example: "2.0"
      id:
        type: string
        example: ""
      result:
        type: object
        properties:
          balance:
            type: object
            description: Map of address' balances
            minProperties: 1
            properties:
              MNT:
                type: string
                example: "10000000000000000000"
          transaction_count:
            type: integer
            example: 1
  StatusResponse:
    type: object
    properties:
      jsonrpc:
        type: string
        example: "2.0"
      id:
        type: string
        example: ""
      result:
        type: object
        properties:
          version:
            type: string
            example: "0.9.5-a8c56270"
          latest_block_hash:
            type: string
            example: "9B3659F6F24F30EF491B3CF239B2E3E87A625096B29DA6F55EBA6B38BF5BEE07"
          latest_app_hash:
            type: string
            example: "CB511A789FB49BDE67DE6F4A8189A80E9614569D0134FC6258556DF40B4B8E80"
          latest_block_height:
            type: string
            example: "359793"
          latest_block_time:
            type: string
            example: "2019-01-15T10:57:13.579973521Z"
          state_history:
            type: string
            enum:
              - "on"
              - "off"
            example: "off"
          tm_status:
            type: object
            properties:
              node_info:
                type: object
                properties:
                  protocol_version:
                    type: object
                    properties:
                      p2p:
                        type: string
                        example: "5"
                      block:
                        type: string
                        example: "8"
                      app:
                        type: string
                        example: "1"
                  id:
                    type: string
                    example: "647e32df3b9c54809b5aca2877d9ba60900bc2d9"
                  listen_addr:
                    type: string
                    example: "tcp://0.0.0.0:26656"
                  network:
                    type: string
                    example: "minter-test-network-28"
                  version:
                    type: string
                    example: "0.27.4"
                  channels:
                    type: string
                    example: "4020212223303800"
                  moniker:
                    type: string
                    example: "minter-node-1.testnet.minter.network"
                  other:
                    type: object
                    properties:
                      tx_index:
                        type: string
                        example: "on"
                        enum:
                          - "on"
                          - "off"
                      rpc_address:
                        type: string
                        example: "tcp://0.0.0.0:26657"
              sync_info:
                type: object
                properties:
                  latest_block_hash:
                    type: string
                    example: "9B3659F6F24F30EF491B3CF239B2E3E87A625096B29DA6F55EBA6B38BF5BEE07"
                  latest_app_hash:
                    type: string
                    example: "CB511A789FB49BDE67DE6F4A8189A80E9614569D0134FC6258556DF40B4B8E80"
                  latest_block_height:
                    type: string
                    example: "359793"
                  latest_block_time:
                    type: string
                    example: "2019-01-15T10:57:13.579973521Z"
                  catching_up:
                    type: boolean
                    example: false
              validator_info:
                type: object
                properties:
                  address:
                    type: string
                    example: "F4935E4169DD647F11E9E01EFB04779D3AC3AA9B"
                  pub_key:
                    type: object
                    properties:
                      type:
                        type: string
                        example: "tendermint/PubKeyEd25519"
                      value:
                        type: string
                        example: "SuHuc+YTbIWwypM6mhNHdYozSIXxCzI4OYpnrC6xU7g="
                  voting_power:
                    type: string
                    example: "0"