version: "3.4"
services:
  minter:
    image: minterteam/minter:0.9.6
    volumes:
      - ~/.minter:/minter
    ports:
      - "8841:8841"
      - "3000:3000"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8841/api/status"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s