[[constraint]]
  revision = "ed77733ec07dfc8a513741138419b8d9d3de9d2d"
  name = "github.com/btcsuite/btcd"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "=1.11.1"

[[constraint]]
  name = "github.com/rs/cors"
  version = "^1.6.0"

[[constraint]]
  name = "github.com/danil-lashin/iavl"
  revision = "83a81c94ee7eb3bd0eb14d6829bd04f22e530e6f"

[[constraint]]
  name = "github.com/tendermint/tendermint"
  version = "0.30.2"

[[constraint]]
  name = "github.com/MinterTeam/go-amino"
  version = "=v0.14.1-m"

[[constraint]]
  branch = "v1"
  name = "gopkg.in/check.v1"

[prune]
  go-tests = true
  unused-packages = true
