# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  branch = "master"
  name = "github.com/btcsuite/btcd"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "=1.11.1"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "=1.6.2"

[[constraint]]
  name = "github.com/rs/cors"
  version = "=1.4.0"

[[constraint]]
  name = "github.com/danil-lashin/iavl"
  branch = "master"

[[constraint]]
  name = "github.com/tendermint/tendermint"
  revision = "5a6822c8acbd7353729cbb5d8393de2f6da39425"

[[constraint]]
  branch = "v1"
  name = "gopkg.in/check.v1"

[prune]
  go-tests = true
  unused-packages = true
